version: "3.8"
services:
  backend:
    build: ./backend
    container_name: ufm-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - ufm-net

  frontend:
    build: ./frontend
    container_name: ufm-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000/api/v1
    depends_on:
      - backend
    networks:
      - ufm-net

networks:
  ufm-net:
    driver: bridge
